version: "3.8"

services:
  liefer_bot_db:
    container_name: "liefer_bot_db"
    restart: always
    image: postgres:12.20-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initiate_database.sql:/docker-entrypoint-initdb.d/initiate_database.sql
    ports:
      - ${DB_EXT_PORT}:5432

  customer_bot:
    build:
      context: .
      dockerfile: Dockerfile_customer_bot
    env_file:
      - .env
    environment:
      - CUSTOMER_BOT_TOKEN=${CUSTOMER_BOT_TOKEN}
      - DEF_LANG=${DEF_LANG}
    container_name: liefer_bot_customer
    restart: always

  restaurant_bot:
    build:
      context: .
      dockerfile: Dockerfile_restaurant_bot
    env_file:
      - .env
    environment:
      - RESTAURANT_BOT_TOKEN=${RESTAURANT_BOT_TOKEN}
      - DEF_LANG=${DEF_LANG}
    container_name: liefer_bot_restaurant
    restart: always

volumes:
  pgdata:
    external: true
