services:
  liefer_bot_db:
    container_name: "liefer_bot_db"
    restart: always
    image: postgres:12.20-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initiate_database.sql:/docker-entrypoint-initdb.d/initiate_database.sql
    ports:
      - ${DB_EXT_PORT?:5432}:5432

  customer_bot:
    build:
      context: .
      dockerfile: customer_bot/Dockerfile
    env_file:
      - .env
    environment:
      - CUSTOMER_BOT_TOKEN=${CUSTOMER_BOT_TOKEN}
      - RESTAURANT_BOT_TOKEN=${RESTAURANT_BOT_TOKEN}
      - COURIER_BOT_TOKEN=${COURIER_BOT_TOKEN}
      - ADMIN_BOT_TOKEN=${ADMIN_BOT_TOKEN}
      - COURIER_FEE_BASE=${COURIER_FEE_BASE}
      - COURIER_FEE_RATE=${COURIER_FEE_RATE}
      - COURIER_FEE_DISTANCE_RATE=${COURIER_FEE_DISTANCE_RATE}
      - SERVICE_FEE_BASE=${SERVICE_FEE_BASE}
      - SERVICE_FEE_RATE=${SERVICE_FEE_RATE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEF_LANG=${DEF_LANG}
      - PP_USERNAME=${PP_USERNAME}
      - PP_PASSWORD=${PP_PASSWORD}
      - PP_MODE=${PP_MODE?:sandbox}
      - BRAND_NAME=${BRAND_NAME}
      - RETURN_LINK=${RETURN_LINK?:https://google.com}
    container_name: liefer_bot_customer
    restart: always

  restaurant_bot:
    build:
      context: .
      dockerfile: restaurant_bot/Dockerfile
    env_file:
      - .env
    environment:
      - CUSTOMER_BOT_TOKEN=${CUSTOMER_BOT_TOKEN}
      - RESTAURANT_BOT_TOKEN=${RESTAURANT_BOT_TOKEN}
      - COURIER_BOT_TOKEN=${COURIER_BOT_TOKEN}
      - ADMIN_BOT_TOKEN=${ADMIN_BOT_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEF_LANG=${DEF_LANG}
      - BRAND_NAME=${BRAND_NAME}
    container_name: liefer_bot_restaurant
    restart: always

  courier_bot:
    build:
      context: .
      dockerfile: courier_bot/Dockerfile
    env_file:
      - .env
    environment:
      - CUSTOMER_BOT_TOKEN=${CUSTOMER_BOT_TOKEN}
      - RESTAURANT_BOT_TOKEN=${RESTAURANT_BOT_TOKEN}
      - COURIER_BOT_TOKEN=${COURIER_BOT_TOKEN}
      - ADMIN_BOT_TOKEN=${ADMIN_BOT_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEF_LANG=${DEF_LANG}
      - BRAND_NAME=${BRAND_NAME}
    container_name: liefer_bot_courier
    restart: always

  admin_bot:
    build:
      context: .
      dockerfile: admin_bot/Dockerfile
    env_file:
      - .env
    environment:
      - CUSTOMER_BOT_TOKEN=${CUSTOMER_BOT_TOKEN}
      - RESTAURANT_BOT_TOKEN=${RESTAURANT_BOT_TOKEN}
      - COURIER_BOT_TOKEN=${COURIER_BOT_TOKEN}
      - ADMIN_BOT_TOKEN=${ADMIN_BOT_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEF_LANG=${DEF_LANG}
      - PP_USERNAME=${PP_USERNAME}
      - PP_PASSWORD=${PP_PASSWORD}
      - PP_MODE=${PP_MODE?:sandbox}
      - BRAND_NAME=${BRAND_NAME}
      - RETURN_LINK=${RETURN_LINK?:https://google.com}
    container_name: liefer_bot_admin
    restart: always

volumes:
  pgdata:
    external: true
